timestamp,category,user_id,function,line_number,flag,message,exception
2024-06-14 14:51:39,ERROR,demo13,create_or_pass_folder,202,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 195, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:f85cd32c-b01e-0009-643c-be6f88000000
Time:2024-06-14T09:21:39.3242537Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f85cd32c-b01e-0009-643c-be6f88000000
Time:2024-06-14T09:21:39.3242537Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error>"
2024-06-14 14:51:39,ERROR,demo13,create_or_pass_folder,211,0,"Function create_or_pass_folder Error creating folder'demo13': Value for one of the query parameters specified in the request URI is invalid.
RequestId:f85cd32c-b01e-0009-643c-be6f88000000
Time:2024-06-14T09:21:39.3242537Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f85cd32c-b01e-0009-643c-be6f88000000
Time:2024-06-14T09:21:39.3242537Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'demo13': Value for one of the query parameters specified in the request URI is invalid.
RequestId:f85cd32c-b01e-0009-643c-be6f88000000
Time:2024-06-14T09:21:39.3242537Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f85cd32c-b01e-0009-643c-be6f88000000
Time:2024-06-14T09:21:39.3242537Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 195, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:f85cd32c-b01e-0009-643c-be6f88000000
Time:2024-06-14T09:21:39.3242537Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:f85cd32c-b01e-0009-643c-be6f88000000
Time:2024-06-14T09:21:39.3242537Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error>"
2024-06-14 14:51:39,INFO,demo13,home,1411,1,User demo13 logged in successfully,
2024-06-14 14:51:39,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 14:51:43,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 14:51:50,INFO,demo13,get_data_source,2371,1,table_update route successfully send data,
2024-06-14 14:52:21,INFO,demo13,perform_lda____summ,1133,1,Summary topics generated.,
2024-06-14 14:52:21,INFO,demo13,handle_summary_input,2082,1,Summary Generated in 22.001485586166382 seconds,
2024-06-14 14:52:52,INFO,demo13,handle_clear_chat_summ,2116,1,Summary chat cleared,
2024-06-14 14:52:55,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-14 14:53:03,INFO,demo13,get_data_source,2371,1,table_update route successfully send data,
