timestamp,category,user_id,function,line_number,flag,message,exception
2024-06-10 12:28:27,ERROR,asif24,create_or_pass_folder,199,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 192, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:2c226ba7-f01e-002c-0b03-bbf73b000000
Time:2024-06-10T06:58:26.9226879Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:2c226ba7-f01e-002c-0b03-bbf73b000000
Time:2024-06-10T06:58:26.9226879Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-10 12:28:27,ERROR,asif24,create_or_pass_folder,208,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:2c226ba7-f01e-002c-0b03-bbf73b000000
Time:2024-06-10T06:58:26.9226879Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:2c226ba7-f01e-002c-0b03-bbf73b000000
Time:2024-06-10T06:58:26.9226879Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:2c226ba7-f01e-002c-0b03-bbf73b000000
Time:2024-06-10T06:58:26.9226879Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:2c226ba7-f01e-002c-0b03-bbf73b000000
Time:2024-06-10T06:58:26.9226879Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 192, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:2c226ba7-f01e-002c-0b03-bbf73b000000
Time:2024-06-10T06:58:26.9226879Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:2c226ba7-f01e-002c-0b03-bbf73b000000
Time:2024-06-10T06:58:26.9226879Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-10 12:28:27,INFO,asif24,home,1408,1,User asif24 logged in successfully,
2024-06-10 12:28:27,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:28:30,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:28:32,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:28:48,INFO,asif24,perform_lda____summ,1124,1,Summary topics generated.,
2024-06-10 12:28:48,INFO,asif24,handle_summary_input,1854,1,Summary Generated in 9.294435262680054 seconds,
2024-06-10 12:29:19,INFO,asif24,perform_lda____summ,1124,1,Summary topics generated.,
2024-06-10 12:29:19,INFO,asif24,handle_summary_input,1854,1,Summary Generated in 11.670587301254272 seconds,
2024-06-10 12:29:26,INFO,asif24,handle_clear_chat_summ,1888,1,Summary chat cleared,
2024-06-10 12:29:43,INFO,asif24,perform_lda____summ,1124,1,Summary topics generated.,
2024-06-10 12:29:43,INFO,asif24,handle_summary_input,1854,1,Summary Generated in 13.512823104858398 seconds,
2024-06-10 12:31:38,INFO,asif24,handle_clear_chat_summ,1888,1,Summary chat cleared,
2024-06-10 12:31:46,ERROR,asif24,create_or_pass_folder,199,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 192, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:b0984866-401e-001c-0204-bbad11000000
Time:2024-06-10T07:01:46.1600247Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b0984866-401e-001c-0204-bbad11000000
Time:2024-06-10T07:01:46.1600247Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-10 12:31:46,ERROR,asif24,create_or_pass_folder,208,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:b0984866-401e-001c-0204-bbad11000000
Time:2024-06-10T07:01:46.1600247Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b0984866-401e-001c-0204-bbad11000000
Time:2024-06-10T07:01:46.1600247Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:b0984866-401e-001c-0204-bbad11000000
Time:2024-06-10T07:01:46.1600247Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b0984866-401e-001c-0204-bbad11000000
Time:2024-06-10T07:01:46.1600247Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 192, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:b0984866-401e-001c-0204-bbad11000000
Time:2024-06-10T07:01:46.1600247Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b0984866-401e-001c-0204-bbad11000000
Time:2024-06-10T07:01:46.1600247Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-10 12:31:46,INFO,asif24,home,1408,1,User asif24 logged in successfully,
2024-06-10 12:31:47,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:31:49,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:31:50,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:31:59,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:31:59,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:32:00,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:32:01,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:32:01,INFO,asif24,delete_files,2020,1,Selected vault files deleted successfully,
2024-06-10 12:32:02,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:32:15,ERROR,asif24,handle_summary_input,1860,0,Summary generation error,"Summary generation error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 1846, in handle_summary_input
    analyze_sentiment_summ(senti_text_summ)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 912, in analyze_sentiment_summ
    senti_Positive_summ = sentiment_scores['pos'] / total * 100
ZeroDivisionError: float division by zero"
2024-06-10 12:32:16,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:32:17,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:32:27,ERROR,asif24,handle_ask_question,1963,0,Ask CogniLink answer generation error,"Ask CogniLink answer generation error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 1929, in handle_ask_question
    doc_source = [response[""source_documents""][0].metadata[""source""]]
IndexError: list index out of range"
2024-06-10 12:32:29,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:32:30,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:32:36,INFO,asif24,upload_to_blob,257,1,Function upload_to_blob successfully created blob_client.url,
2024-06-10 12:32:36,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:32:36,INFO,asif24,popup_form,1539,1,Data Uploaded Successfully,
2024-06-10 12:32:36,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:32:40,INFO,asif24,Cogni_button,1722,1,CogniLink load button pressed,
2024-06-10 12:32:50,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 12:32:52,INFO,asif24,update_when_file_delete,607,1,Function update_when_file_delete Data Loaded Successfully,
2024-06-10 12:32:52,INFO,asif24,Cogni_button,1734,1,Load Data Function executed in 12.1820068359375 seconds,
2024-06-10 12:32:53,INFO,asif24,get_data_source,2058,1,table_update route successfully send data,
2024-06-10 12:33:08,INFO,asif24,perform_lda____summ,1124,1,Summary topics generated.,
2024-06-10 12:33:08,INFO,asif24,handle_summary_input,1854,1,Summary Generated in 7.50984787940979 seconds,
