timestamp,category,user_id,function,line_number,flag,message,exception
2024-06-09 23:59:55,ERROR,asif24,create_or_pass_folder,199,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 192, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:8498ea3d-901e-005a-409b-ba7387000000
Time:2024-06-09T18:29:54.2803179Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:8498ea3d-901e-005a-409b-ba7387000000
Time:2024-06-09T18:29:54.2803179Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-09 23:59:55,ERROR,asif24,create_or_pass_folder,208,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:8498ea3d-901e-005a-409b-ba7387000000
Time:2024-06-09T18:29:54.2803179Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:8498ea3d-901e-005a-409b-ba7387000000
Time:2024-06-09T18:29:54.2803179Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:8498ea3d-901e-005a-409b-ba7387000000
Time:2024-06-09T18:29:54.2803179Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:8498ea3d-901e-005a-409b-ba7387000000
Time:2024-06-09T18:29:54.2803179Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\app.py"", line 192, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\New_version_CogniLink\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:8498ea3d-901e-005a-409b-ba7387000000
Time:2024-06-09T18:29:54.2803179Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:8498ea3d-901e-005a-409b-ba7387000000
Time:2024-06-09T18:29:54.2803179Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-06-09 23:59:55,INFO,asif24,home,1408,1,User asif24 logged in successfully,
2024-06-09 23:59:55,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-09 23:59:59,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 00:00:03,INFO,asif24,get_data_source,2056,1,table_update route successfully send data,
2024-06-10 00:00:08,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 00:00:08,INFO,asif24,get_data_source,2056,1,table_update route successfully send data,
2024-06-10 00:01:45,INFO,asif24,upload_to_blob,257,1,Function upload_to_blob successfully created blob_client.url,
2024-06-10 00:01:45,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 00:01:45,INFO,asif24,popup_form,1539,1,Data Uploaded Successfully,
2024-06-10 00:01:46,INFO,asif24,get_data_source,2056,1,table_update route successfully send data,
2024-06-10 00:02:02,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 00:02:03,INFO,asif24,get_data_source,2056,1,table_update route successfully send data,
2024-06-10 00:02:40,INFO,asif24,upload_to_blob,257,1,Function upload_to_blob successfully created blob_client.url,
2024-06-10 00:02:41,INFO,asif24,update_bar_chart_from_blob,319,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-10 00:02:41,INFO,asif24,popup_form,1539,1,Data Uploaded Successfully,
2024-06-10 00:02:41,INFO,asif24,get_data_source,2056,1,table_update route successfully send data,
2024-06-10 00:02:58,ERROR,asif24,delete_files,2013,0,delete for delete route: draft not found,"delete for delete route: draft not found
NoneType: None"
2024-06-10 00:02:59,INFO,asif24,get_data_source,2056,1,table_update route successfully send data,
