timestamp,category,user_id,function,line_number,flag,message,exception
2024-07-03 09:44:49,ERROR,asif24,create_or_pass_folder,226,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:b4ec461c-201e-006a-2cff-cc29ad000000
Time:2024-07-03T04:14:48.2387188Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b4ec461c-201e-006a-2cff-cc29ad000000
Time:2024-07-03T04:14:48.2387188Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 09:44:49,ERROR,asif24,create_or_pass_folder,235,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:b4ec461c-201e-006a-2cff-cc29ad000000
Time:2024-07-03T04:14:48.2387188Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b4ec461c-201e-006a-2cff-cc29ad000000
Time:2024-07-03T04:14:48.2387188Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:b4ec461c-201e-006a-2cff-cc29ad000000
Time:2024-07-03T04:14:48.2387188Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b4ec461c-201e-006a-2cff-cc29ad000000
Time:2024-07-03T04:14:48.2387188Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:b4ec461c-201e-006a-2cff-cc29ad000000
Time:2024-07-03T04:14:48.2387188Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b4ec461c-201e-006a-2cff-cc29ad000000
Time:2024-07-03T04:14:48.2387188Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 09:44:49,INFO,asif24,home,1704,1,User asif24 logged in successfully,
2024-07-03 09:44:49,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 09:44:53,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 09:44:56,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 09:44:56,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 09:58:05,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 09:58:05,INFO,asif24,popup_form,2002,1,Data Uploaded Successfully,
2024-07-03 09:58:08,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 09:58:08,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 10:05:16,INFO,asif24,Cogni_button,2185,1,CogniLink load button pressed,
2024-07-03 10:05:26,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 10:05:36,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 10:05:36,INFO,asif24,update_when_file_delete,778,1,Function update_when_file_delete Data Loaded Successfully,
2024-07-03 10:05:36,INFO,asif24,Cogni_button,2197,1,Load Data Function executed in 19.484473705291748 seconds,
2024-07-03 10:05:40,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 10:05:40,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:15:17,ERROR,asif24,create_or_pass_folder,226,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:3fd98524-901e-0078-600c-cd1db1000000
Time:2024-07-03T05:45:16.4208478Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:3fd98524-901e-0078-600c-cd1db1000000
Time:2024-07-03T05:45:16.4208478Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 11:15:17,ERROR,asif24,create_or_pass_folder,235,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:3fd98524-901e-0078-600c-cd1db1000000
Time:2024-07-03T05:45:16.4208478Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:3fd98524-901e-0078-600c-cd1db1000000
Time:2024-07-03T05:45:16.4208478Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:3fd98524-901e-0078-600c-cd1db1000000
Time:2024-07-03T05:45:16.4208478Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:3fd98524-901e-0078-600c-cd1db1000000
Time:2024-07-03T05:45:16.4208478Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:3fd98524-901e-0078-600c-cd1db1000000
Time:2024-07-03T05:45:16.4208478Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:3fd98524-901e-0078-600c-cd1db1000000
Time:2024-07-03T05:45:16.4208478Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 11:15:17,INFO,asif24,home,1704,1,User asif24 logged in successfully,
2024-07-03 11:15:17,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:20,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:24,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:24,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:15:27,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:31,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:31,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:15:32,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:36,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:36,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:15:43,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:43,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:15:45,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:49,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:15:49,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:16:02,INFO,asif24,upload_to_blob,295,1,Function upload_to_blob successfully uploaded the blob,
2024-07-03 11:16:02,INFO,asif24,upload_to_blob,298,1,Function upload_to_blob successfully uploaded the blob,
2024-07-03 11:16:03,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:16:03,INFO,asif24,popup_form,2002,1,Data Uploaded Successfully,
2024-07-03 11:16:07,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:16:07,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:16:18,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:16:18,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:16:20,INFO,asif24,handle_eda_process,3331,1,SocketIO Eda_Process File name received,
2024-07-03 11:16:22,INFO,asif24,handle_eda_process,3349,1,SocketIO Eda_Process Data Loaded Successfully.,
2024-07-03 11:16:30,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:16:30,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:16:31,INFO,asif24,handle_eda_process,3357,1,SocketIO Eda_Process Question received.,
2024-07-03 11:16:49,INFO,asif24,handle_eda_process,3377,1,SocketIO Eda_Process output received.,
2024-07-03 11:16:49,INFO,asif24,handle_eda_process,3417,1,SocketIO Eda_Process response emitted.,
2024-07-03 11:17:25,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:17:30,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:17:30,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:19:39,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:19:44,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:19:44,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:20:09,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:20:14,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:20:14,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:24:30,INFO,asif24,Cogni_button,2185,1,CogniLink load button pressed,
2024-07-03 11:24:41,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:24:41,INFO,asif24,update_when_file_delete,778,1,Function update_when_file_delete Data Loaded Successfully,
2024-07-03 11:24:41,INFO,asif24,Cogni_button,2197,1,Load Data Function executed in 11.172281503677368 seconds,
2024-07-03 11:24:46,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:24:46,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:25:14,INFO,asif24,perform_lda____summ,1391,1,Summary topics generated.,
2024-07-03 11:25:14,INFO,asif24,handle_summary_input,2426,1,Summary Generated in 4.141733407974243 seconds,
2024-07-03 11:25:22,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:25:26,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:25:26,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:25:47,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:25:47,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:25:50,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:25:50,INFO,asif24,delete_files,2655,1,Selected vault files deleted successfully,
2024-07-03 11:25:51,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:25:51,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:25:53,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:25:53,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:25:55,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:25:55,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:25:57,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:25:57,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:26:05,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:26:05,INFO,asif24,popup_form,2002,1,Data Uploaded Successfully,
2024-07-03 11:26:07,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:26:07,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:26:42,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:26:42,INFO,asif24,popup_form,2002,1,Data Uploaded Successfully,
2024-07-03 11:26:44,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:26:44,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:27:06,INFO,asif24,Cogni_button,2185,1,CogniLink load button pressed,
2024-07-03 11:27:15,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:27:21,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:27:29,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:27:29,INFO,asif24,update_when_file_delete,778,1,Function update_when_file_delete Data Loaded Successfully,
2024-07-03 11:27:29,INFO,asif24,Cogni_button,2197,1,Load Data Function executed in 23.55649733543396 seconds,
2024-07-03 11:27:33,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:27:33,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
2024-07-03 11:27:54,ERROR,asif24,handle_summary_input,2432,0,Summary generation error,"Summary generation error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 2410, in handle_summary_input
    summary = custom_summary(document, custom_p, chain_type)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 1102, in custom_summary
    summaries = chain({""input_documents"": docs}, return_only_outputs=True)[""output_text""]
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\_api\deprecation.py"", line 148, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 378, in __call__
    return self.invoke(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 163, in invoke
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\combine_documents\base.py"", line 137, in _call
    output, extra_return_dict = self.combine_docs(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\combine_documents\map_reduce.py"", line 226, in combine_docs
    map_results = self.llm_chain.apply(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 250, in apply
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 247, in apply
    response = self.generate(input_list, run_manager=run_manager)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 138, in generate
    return self.llm.generate_prompt(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 560, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 421, in generate
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 411, in generate
    self._generate_with_cache(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 632, in _generate_with_cache
    result = self._generate(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_community\chat_models\openai.py"", line 441, in _generate
    response = self.completion_with_retry(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_community\chat_models\openai.py"", line 356, in completion_with_retry
    return self.client.create(**kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_utils\_utils.py"", line 277, in wrapper
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\resources\chat\completions.py"", line 590, in create
    return self._post(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 921, in request
    return self._request(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': ""The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766"", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400}}"
2024-07-03 11:28:08,ERROR,asif24,handle_summary_input,2432,0,Summary generation error,"Summary generation error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 2410, in handle_summary_input
    summary = custom_summary(document, custom_p, chain_type)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 1102, in custom_summary
    summaries = chain({""input_documents"": docs}, return_only_outputs=True)[""output_text""]
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\_api\deprecation.py"", line 148, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 378, in __call__
    return self.invoke(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 163, in invoke
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\combine_documents\base.py"", line 137, in _call
    output, extra_return_dict = self.combine_docs(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\combine_documents\map_reduce.py"", line 226, in combine_docs
    map_results = self.llm_chain.apply(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 250, in apply
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 247, in apply
    response = self.generate(input_list, run_manager=run_manager)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 138, in generate
    return self.llm.generate_prompt(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 560, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 421, in generate
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 411, in generate
    self._generate_with_cache(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 632, in _generate_with_cache
    result = self._generate(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_community\chat_models\openai.py"", line 441, in _generate
    response = self.completion_with_retry(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_community\chat_models\openai.py"", line 356, in completion_with_retry
    return self.client.create(**kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_utils\_utils.py"", line 277, in wrapper
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\resources\chat\completions.py"", line 590, in create
    return self._post(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 921, in request
    return self._request(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': ""The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766"", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400}}"
2024-07-03 11:28:21,ERROR,asif24,handle_summary_input,2432,0,Summary generation error,"Summary generation error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 2410, in handle_summary_input
    summary = custom_summary(document, custom_p, chain_type)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 1102, in custom_summary
    summaries = chain({""input_documents"": docs}, return_only_outputs=True)[""output_text""]
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\_api\deprecation.py"", line 148, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 378, in __call__
    return self.invoke(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 163, in invoke
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\base.py"", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\combine_documents\base.py"", line 137, in _call
    output, extra_return_dict = self.combine_docs(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\combine_documents\map_reduce.py"", line 226, in combine_docs
    map_results = self.llm_chain.apply(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 250, in apply
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 247, in apply
    response = self.generate(input_list, run_manager=run_manager)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain\chains\llm.py"", line 138, in generate
    return self.llm.generate_prompt(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 560, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 421, in generate
    raise e
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 411, in generate
    self._generate_with_cache(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\language_models\chat_models.py"", line 632, in _generate_with_cache
    result = self._generate(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_community\chat_models\openai.py"", line 441, in _generate
    response = self.completion_with_retry(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_community\chat_models\openai.py"", line 356, in completion_with_retry
    return self.client.create(**kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_utils\_utils.py"", line 277, in wrapper
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\resources\chat\completions.py"", line 590, in create
    return self._post(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 921, in request
    return self._request(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\openai\_base_client.py"", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': ""The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766"", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400}}"
2024-07-03 11:28:31,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:28:35,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 11:28:35,INFO,asif24,get_data_source,2978,1,table_update route successfully sent data,
