timestamp,category,user_id,function,line_number,flag,message,exception
2024-07-03 13:30:42,ERROR,asif24,create_or_pass_folder,226,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:6a886674-601e-000b-711f-cd6d72000000
Time:2024-07-03T08:00:41.4543703Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:6a886674-601e-000b-711f-cd6d72000000
Time:2024-07-03T08:00:41.4543703Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 13:30:42,ERROR,asif24,create_or_pass_folder,235,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:6a886674-601e-000b-711f-cd6d72000000
Time:2024-07-03T08:00:41.4543703Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:6a886674-601e-000b-711f-cd6d72000000
Time:2024-07-03T08:00:41.4543703Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:6a886674-601e-000b-711f-cd6d72000000
Time:2024-07-03T08:00:41.4543703Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:6a886674-601e-000b-711f-cd6d72000000
Time:2024-07-03T08:00:41.4543703Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:6a886674-601e-000b-711f-cd6d72000000
Time:2024-07-03T08:00:41.4543703Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:6a886674-601e-000b-711f-cd6d72000000
Time:2024-07-03T08:00:41.4543703Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 13:30:42,INFO,asif24,home,1704,1,User asif24 logged in successfully,
2024-07-03 13:30:42,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:30:45,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:30:48,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:30:48,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:30:53,INFO,asif24,Cogni_button,2338,1,CogniLink load button pressed,
2024-07-03 13:30:54,INFO,asif24,Cogni_button,2350,1,Load Data Function executed in 1.3663454055786133 seconds,
